CREATE TABLE TBL_MEMBER(
	userid VARCHAR2(100) PRIMARY KEY,
	userpw VARCHAR2(100),
	username VARCHAR2(100),
	usergender VARCHAR2(100),
	userphone VARCHAR2(100),
	userpostcode VARCHAR2(100),
	useraddr  VARCHAR2(300),
	useraddrdetail VARCHAR2(300),
	useraddretc VARCHAR2(300)
);
INSERT INTO TBL_MEMBER (USERID,USERPW,USERNAME) VALUES('admin','admin','관리자');
DROP TABLE TBL_MEMBER;
SELECT * FROM TBL_MEMBER;

CREATE TABLE TBL_BOARD(
	BOARDNUM NUMBER(10) PRIMARY KEY,
	BOARDTITLE VARCHAR2(200),
	BOARDCONTENTS VARCHAR2(3999),
	USERID VARCHAR2(100),
	BOARDDATE DATE,
	BOARDREADCOUNT NUMBER(6),
	CONSTRAINTS BOARD_USER_FK FOREIGN KEY(USERID) REFERENCES TBL_MEMBER(USERID)
);
DROP TABLE TBL_BOARD;

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

DROP SEQUENCE BOARD_SEQ;


INSERT INTO TBL_BOARD
VALUES(BOARD_SEQ.NEXTVAL,'테스트용 게시글1','재미있는 게시판 만들기','apple',SYSDATE,0);
INSERT INTO TBL_BOARD
VALUES(BOARD_SEQ.NEXTVAL,'테스트용 게시글2','너무 쉬운 게시판 만들기','apple',SYSDATE,0);
INSERT INTO TBL_BOARD
VALUES(BOARD_SEQ.NEXTVAL,'테스트용 게시글3','공지사항','admin',SYSDATE,0);
SELECT * FROM TBL_BOARD ORDER BY BOARDNUM desc;

CREATE TABLE TBL_FILE(
	BOARDNUM NUMBER(10),
	FILENAME VARCHAR2(300),
	REALNAME VARCHAR2(300),
	CONSTRAINT FILE_BOARD_FK FOREIGN KEY(BOARDNUM) REFERENCES TBL_BOARD(BOARDNUM)
);
DROP TABLE TBL_FILE;

SELECT * FROM TBL_FILE;

CREATE TABLE TBL_REPLY(
	REPLYNUM NUMBER(11) PRIMARY KEY,
	REPLYCONTENTS VARCHAR2(1000),
	USERID VARCHAR2(100),
	BOARDNUM NUMBER(10),
	CONSTRAINT REPLY_USER_FK FOREIGN KEY(USERID) REFERENCES TBL_MEMBER(USERID),
	CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(BOARDNUM) REFERENCES TBL_BOARD(BOARDNUM)
);
DROP TABLE TBL_REPLY;

CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

DROP SEQUENCE reply_seq;

SELECT * FROM TBL_REPLY;




